version: '{build}'
image: WMF 5

environment:
  mail_user: majkinetor@gmail.com

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable

build_script:
- ps: |
    ib build

test_script:
- ps: |
    $res = ib test

    "Uploading test results"
    $url = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
    (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path _build/*/TestResults.xml))
    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed." }

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: .

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

